name: Docker rebuild on requirements change

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'requirements.txt'
      - 'Project.toml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'requirements.txt'
      - 'Project.toml'

jobs:
  call-docker-workflow:
    uses: ${{ github.repository }}/.github/workflows/docker-publish.yml@docker