name: Docker rebuild on requirements change

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'requirements.txt'
      - 'Project.toml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'requirements.txt'
      - 'Project.toml'

jobs:
  call-docker-workflow:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ltpn/snedoqs-tutorials/.github/workflows/docker-publish.yml@docker
    secrets: inherit
